### ISSUE TITLE
new arp module error

### ISSUE THREAD

**Issue by therealtear** [roccomuso/kickthemout#14]
Scanning LAN.. -/usr/local/lib/node_modules/kickthemout/lib/Network.js:48
              if (getmac.isMac(mac)) {
                         ^

TypeError: getmac.isMac is not a function
    at /usr/local/lib/node_modules/kickthemout/lib/Network.js:48:26
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/kickthemout/node_modules/node-arp/lib/arp.js:168:5)

**Comment by roccomuso** [comment]
This old repo doesn't have a `package-lock.json` or `yarn.lock` file for dependencies.
During install maybe a version of `getmac` with api changes got installed. What version are you using? could you check if downgrading helps?

**Comment by therealtear** [comment]
> This old repo doesn't have a `package-lock.json` or `yarn.lock` file for dependencies.
> During install maybe a version of `getmac` with api changes got installed. What version are you using? could you check if downgrading helps?

I changed the package.json to use all the most recent modules possible and I believe it was simply a change with getmac a simple downgrade was enough to fix the issue but I will keep looking into how the newer versions of the modules used work to push a slightly more updated version as it doesn't seem to be actually workiny on both my raspberry pi 4 or my macbook pro

**Comment by roccomuso** [comment]
Can you open a pull request so we can push package-lock.json and avoid this issue for other users?

thanks
