### ISSUE TITLE
forgot to mention updating mac vendors db with oui doesnt seem to be working either

### ISSUE THREAD

**Issue by therealtear** [roccomuso/kickthemout#16]
waiting upwards of 30 minutes and I never got a success message

**Comment by roccomuso** [comment]
What kind of success messagge did you expect?

This is how it should looks like: https://asciinema.org/a/100375

"Attack running..." means it's working.

**Comment by therealtear** [comment]
![Screen Shot 2021-03-16 at 11 20 28 AM](https://user-images.githubusercontent.com/63162279/111352279-9e35e980-8649-11eb-9b15-c3db6f9a3507.png)

I meant updating mac vendors list but also when I run an attack it never disconnects any device

**Comment by roccomuso** [comment]
we'll eventually deprecate that

**Comment by therealtear** [comment]
ok
