### ISSUE TITLE
Freeze at start

### ISSUE THREAD

**Issue by aube-io** [roccomuso/kickthemout#6]
freeze when you select run "Start KickThemOut", we cant press any key (ctrl + c to exit or arrow to choose the Interface)

**Comment by roccomuso** [comment]
@florenthagard Can you give me more details on your running environment to be able to reproduce the issue?

- Current OS?
- Node version?
- Kickthemout version?
- Have you installed the native dependencies? `libpcap`.

**Comment by aube-io** [comment]
Max OSX Sierra (Darwin 16.6.0)
node v8.1.2
KickThemOut v (latest)
libpcap is install

**Comment by roccomuso** [comment]
@florenthagard Could you test it with a minor version of Node? Like 4 or 5.
Also activate the debug with: `DEBUG=kickthemout:* kickthemout` and past your console log here.

Thanks
